### ISSUE TITLE
Enhance error message if one tries to hash password with newline

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-auth-service#106]
As described here https://github.com/OpenSlides/openslides-manage-service/issues/86 the auth service provides a unhelpful error message if someone tries to hash a password containing a newline or linefeed. Maybe add a check that such invalid characters are not present and provide a nice error message.

**Comment by GabrielInTheWorld** [comment]
I cannot reproduce this error.

Sending 
```
curl http://localhost:9004/internal/auth/hash -d '{"toHash": "a password\n\r"}' -H "Content-Type: application/json"
```

works fine and gives me the following response
```json
{"message":"Action handled successfully","success":true,"hash":"4293a70c1a04e2fe5a15d5ac5a9116c1875182c85be292762834b3349827aa69MzUuz8g0UY6MwUNIV1nLm47hnICaslynDzBskh0IyMY9o0KC4VXOZ68VMW6I1jlgra68FfDU1DSGDeWb5qTkCw=="}
```

The same goes for the data `{"toHash": "a password\n"}` and `{"toHash": "a password\r"}`.

Write a "walkthrough" to reproduce the error, if you still think, it is an auth-service's bug.

**Comment by GabrielInTheWorld** [comment]
I will close this due to inactivity.
