### ISSUE TITLE
Dont't log password hashes

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-auth-service#114]
Currently, when a user logs in, the auth server logs the data it receives from the datastore. It also logs the password hash from the user.

```
docker-auth-1              |   '5978': {
docker-auth-1              |     username: 'm1dummy1975',
docker-auth-1              |     password: '9328fa74e9d51b750f2314bfbd35261a27c4c860202fec1724415227727c4d96hQyW4LyTKbEwcyGgP85PyHtl0s+Seop1qeEMRz9KX4PSQMJZOxl5iiG5deuUi4h325gxc8yFRuAVNMv7nClbGQ==',
docker-auth-1              |     id: 5978,
docker-auth-1              |     is_active: true,
docker-auth-1              |     meta_deleted: false
docker-auth-1              |   }
docker-auth-1              | }
```

The password hash should be considered a secret and not saved in the logs that can be seen by many people.

I only tested this in the dev environment. But I think the password should not be logged even in development. Someone could set the dev-environment variable in production by accident.

**Comment by GabrielInTheWorld** [comment]
> Currently, when a user logs in, the auth server logs the data it receives from the datastore. It also logs the password hash from the user.
> 
> ```
> docker-auth-1              |   '5978': {
> docker-auth-1              |     username: 'm1dummy1975',
> docker-auth-1              |     password: '9328fa74e9d51b750f2314bfbd35261a27c4c860202fec1724415227727c4d96hQyW4LyTKbEwcyGgP85PyHtl0s+Seop1qeEMRz9KX4PSQMJZOxl5iiG5deuUi4h325gxc8yFRuAVNMv7nClbGQ==',
> docker-auth-1              |     id: 5978,
> docker-auth-1              |     is_active: true,
> docker-auth-1              |     meta_deleted: false
> docker-auth-1              |   }
> docker-auth-1              | }
> ```
> 
> The password hash should be considered a secret and not saved in the logs that can be seen by many people.
> 
> I only tested this in the dev environment. But I think the password should not be logged even in development. Someone could set the dev-environment variable in production by accident.

They are logged for developing purposes. Therefore, they won't be removed.
