### ISSUE TITLE
Listen on Signal Interrupt and SIGTERM

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-auth-service#149]
The service has to listen on Interrupt and sigterm and shutdown.

Currently, if you stop the docker container, it waits for the timeout (after 10 seconds) before it stops. This annoying.

**Comment by jsangmeister** [comment]
When does this happen for you? When I stop the dev or test setup, It takes less than a second for me.

**Comment by jsangmeister** [comment]
Thanks! Seems like it only happens in the productive setup. It also looks like https://github.com/OpenSlides/openslides-auth-service/pull/146 already fixes this (see changes in `auth/src/index.ts`).

**Comment by ostcar** [comment]
This does not work. The auth service still waits for 10 seconds until it gets its timeout
