### ISSUE TITLE
Requests from Backend are blocked

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-auth-service#15]
How to replicate:

- checkout openslides4-dev
- `cd openslides-client && git checkout master && git pull upstream master` (assuming `upstream` is set correctly)
- `cd ../openslides-backend && git checkout master && git pull upstream master` (s.a.)
- go to `http://localhost:8000/topics/new` and try to create a topic

Output:

    backend_1               | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): auth:9004
    auth_1                  | [22.07.2020 -- 07:16:54]: [ 'POST -- /' ]
    auth_1                  | [22.07.2020 -- 07:16:54]: [ ' -- blocked.' ]
    backend_1               | DEBUG:urllib3.connectionpool:http://auth:9004 "POST / HTTP/1.1" 200 54
    backend_1               | DEBUG:openslides_backend.services.authentication:Get repsonse: {'success': False, 'message': 'Domain has been blocked!'}

**Comment by FinnStutzenstein** [comment]
CORS needs to be enabled I guess. Or there is another "protective" middleware active

**Comment by GabrielInTheWorld** [comment]
CORS is enabled. The auth-service blocks undefined and not registered domains.

**Comment by FinnStutzenstein** [comment]
Sorry, typo: It needs to be *disabled*!
