### ISSUE TITLE
Stable crypto keys

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-auth-service#21]
Hi, please add a environment variable: `CREATE_KEYS` with default to 0. Only execute the key generation, if it is 1. Set it to one in your docker-compose files.

The goal: Have the same keys for every instance of the service -> They will be mounted via a volume into the containers (for the upcoming swarm setup). I will also do it in the dev version. Why? I cannot test your hard-coded tokens in the client since I have other keys. I will create some default ones, so we all share the same keys during development. Is the path `/tmp/keys` ok or do you want to change it?

**Comment by GabrielInTheWorld** [comment]
Yes, path `/tmp/keys` is okay.
