### ISSUE TITLE
Set alg in ticket

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-auth-service#38]
Currently the jwt tokens write in the headers, that they use the alg "HS256". But this seams wrong. Thins we use RSA Tokens, I would expect the alg to be something like "RS256".

Here is the line where the algo has to be specified:

https://github.com/OpenSlides/openslides-auth-service/blob/5e802f2eae13c1dc51c792e0adb43f78ac0b8c9f/auth/src/api/services/ticket-service.ts#L130

Here is the docu for this function:
https://www.npmjs.com/package/jsonwebtoken#usage

Here is an example. I used the header of the token (first part before the first dot) and decoded as. As you can see, it says, that it uses a HS256 algo. 
```
$ base64 --decode 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
{"alg":"HS256","typ":"JWT"}
```

**Comment by ostcar** [comment]
I digged a bit deeper into this.

As it seems, the token are not signed with RSA. They are signed with HS256 and the secured is the content of the file `rsa-<token|cookie>.key`-file. So the file is not interpreted as rsa-key, but just as some bytes. You could also write `foobar` into this files and it would still work.

To verify the token with HS256, it needs the same bytes then for signing. Therefore the token is verified with the private key and not (as you would expect for an asyncon algo) with the public keyfile:

https://github.com/OpenSlides/openslides-auth-service/blob/5e802f2eae13c1dc51c792e0adb43f78ac0b8c9f/auth/src/api/services/ticket-service.ts#L46-L56

There is another thing. The jwt-library you use expects the public key to be in the PEM format:

https://www.npmjs.com/package/jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback

The format of the two dev keys is currently not in PEM format, but in some kind of ssh-authorized-key format.

And I also think, that the private key is malformed. Neither openssl nor the golang rsa-lib can read it. For example this command should create a public key from the private-key file:

```
$ openssl rsa -in rsa-token.key -outform PEM -pubout -out rsa-token.pub.new
unable to load Private Key
140128969414016:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
```
How did you create the keys?

**Comment by GabrielInTheWorld** [comment]
Closing this isssue, because it is not relevant anymore.
