### ISSUE TITLE
Link existing account to SAML account

### ISSUE THREAD

**Issue by reesericci** [OpenSlides/openslides-auth-service#393]
I'm rolling out SSO in my organization and have found it to be seemingly impossible to be able to link existing OpenSlides accounts to new SAML accounts, only create new OpenSlides accounts

**Comment by hjanott** [comment]
For a good entry point to SAML configuration we updated the wiki page and refer to the necessary action documentation. Please let us know if anything is missing and respectively reopen this or create a new issue. 
https://github.com/OpenSlides/OpenSlides/wiki/SSO
