### ISSUE TITLE
Hash function not working correctly

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-auth-service#41]
Easy test (assuming `auth` is a reference to the `AuthHandler` of the pip library):
```
auth.is_equals("x", auth.hash("x")) // False
auth.is_equals(auth.hash("x"), "x") // False
```
Note that I tested both orders since the documention in https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/interfaces/auth-service.txt it is not quite clear which should be the hashed value. I _think_ the first approach is the right one, but it should be written more clearly.

Either way, as far as I understood the function this is wrong behaviour. Please fix ASAP so the backend can work on the password related functions. If I did something wrong, please tell me what and document it somewhere...

**Comment by GabrielInTheWorld** [comment]
Will be fixed in #42 .
