### ISSUE TITLE
How to sync groups with saml?

### ISSUE THREAD

**Issue by FReichelt** [OpenSlides/openslides-auth-service#430]
Hello,
I was looking for a way to sync groups, f.e. superadmin with SAML, but wasn't able to find any documentation. When looking at the auth-service(https://github.com/OpenSlides/openslides-auth-service/blob/main/auth/src/api/services/auth-service.ts) I wasn't able to find out where and even if group syncing was possible. I'd be really happy to get some information about this topic.

Thanks in advance :)

**Comment by Airfooox** [comment]
I'd like to add to the question of syncing groups:
Is it somehow possible to use the data/groups from SAML/SSO to assign the newly added account to certain committees and keeping the comittee assignments up to date?

This would be pretty important for committees where many people would be eligible in participating ("Mitgliederversammlungen") on many different levels. Managing this manually would be really difficult.

**Comment by rrenkert** [comment]
With https://github.com/OpenSlides/openslides-backend/pull/2722 we implemented a mapping for meetings and meeting attributes for sync with SAML providers.
You can find some basic documentation in 
https://github.com/OpenSlides/openslides-backend/blob/main/docs/actions/user.save_saml_account.md
There are still some (minor) issues and we will improve documentation but maybe this helps you.

**Comment by hjanott** [comment]
For a good entry point to SAML configuration we updated the wiki page and refer to the necessary action documentation. Please let us know if anything is missing and respectively reopen this or create a new issue. 
https://github.com/OpenSlides/OpenSlides/wiki/SSO
