### ISSUE TITLE
Auth service does not finish request

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-auth-service#51]
This is oberservable in the dev setup: Log yourself in and go to the start page. Refresh. Wait for >10 Minutes (It must have something todo with letting the ticket expire, so the auth service must refresh it.). Reload again. The client tries to fets `mediafile/3` as the logo:

- A request to `/system/media/get/3` (mediaservice) is issued.
- The mediaservice sends `[{'presenter': 'check_mediafile_id', 'data': {'mediafile_id': 3}}]` to `http://backend:9003/system/presenter`
- The backend sends a request to the auth service (The authentication header is missing in the logs, only the cookie is printed. Maybe @GabrielInTheWorld can adjust the logging in the auth adapter)
- I've got a huge traceback originating with `OSError: [Errno 107] Transport endpoint is not connected`
```
Traceback (most recent call last):
backend_1           |   File "/app/openslides_backend/services/auth/adapter.py", line 35, in authenticate
backend_1           |     return self.auth_handler.authenticate(headers, cookies)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/auth_handler.py", line 28, in authenticate
backend_1           |     return self.validator.verify(headers, cookies)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/validator.py", line 30, in verify
backend_1           |     token_encoded, cookie_encoded = self.__extractTokenAndCookie(
backend_1           |   File "/usr/local/lib/python3.8/site-packages/authlib/validator.py", line 47, in __extractTokenAndCookie
backend_1           |     raise AuthenticateException("Wrong format of headers")
backend_1           | authlib.exceptions.AuthenticateException: Wrong format of headers
backend_1           | 
backend_1           | During handling of the above exception, another exception occurred:
backend_1           | 
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
backend_1           |     self.handle_request(listener, req, client, addr)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
backend_1           |     respiter = self.wsgi(environ, resp.start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 128, in __call__
backend_1           |     return self.wsgi_application(environ, start_response)
backend_1           |   File "/app/openslides_backend/http/application.py", line 118, in wsgi_application
backend_1           |     response = self.dispatch_request(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 49, in dispatch_request
backend_1           |     return self.default_route(request)
backend_1           |   File "/app/openslides_backend/http/application.py", line 74, in default_route
backend_1           |     response_body, access_token = view_instance.dispatch(
backend_1           |   File "/app/openslides_backend/http/views.py", line 97, in dispatch
backend_1           |     user_id, access_token = self.get_user_id_from_headers(headers, cookies)
backend_1           |   File "/app/openslides_backend/http/views.py", line 32, in get_user_id_from_headers
backend_1           |     user_id, access_token = self.services.authentication().authenticate(
backend_1           |   File "/app/openslides_backend/services/auth/adapter.py", line 37, in authenticate
backend_1           |     self.logger.debug(f"Error in auth service: {e.message}")
backend_1           | AttributeError: 'AuthenticateException' object has no attribute 'message'
backend_1           | [2020-11-17 08:22:59 +0000] [132] [ERROR] Socket error processing request.
backend_1           | Traceback (most recent call last):
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 133, in handle
backend_1           |     req = next(parser)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/parser.py", line 41, in __next__
backend_1           |     self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 186, in __init__
backend_1           |     super().__init__(cfg, unreader)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 53, in __init__
backend_1           |     unused = self.parse(self.unreader)
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 235, in parse
backend_1           |     self.headers = self.parse_headers(data[:idx])
backend_1           |   File "/usr/local/lib/python3.8/site-packages/gunicorn/http/message.py", line 73, in parse_headers
backend_1           |     remote_addr = self.unreader.sock.getpeername()
backend_1           | OSError: [Errno 107] Transport endpoint is not connected
```
    Note: There are also other errors, that have to be resolved, like the `AttributeError`. It seems, that it is not well tested in conjunction
- The only logs from the auth service is
```
auth_1              | BadRequestError: request aborted
auth_1              |     at IncomingMessage.onAborted (/app/node_modules/raw-body/index.js:231:10)
auth_1              |     at IncomingMessage.emit (events.js:315:20)
auth_1              |     at abortIncoming (_http_server.js:561:9)
auth_1              |     at socketOnClose (_http_server.js:554:3)
auth_1              |     at Socket.emit (events.js:327:22)
auth_1              |     at TCP.<anonymous> (net.js:673:12)
```

First, please add more (debug) logging to the auth service, e.g. when a request is received, which payxload, which url. Also a debug statement about the result of the request. Currently I can only trace it to the request the backend sends, after this is only silence and guessing from my side.

Finally, the backend gets killed and restarted by gunicorn because the worker timed out:
```
backend_1           | [2020-11-17 08:22:58 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:130)
backend_1           | [2020-11-17 08:22:58 +0000] [130] [INFO] Worker exiting (pid: 130)
```
This message is acutally before the logs of the auth service, so it is clear why the auth logs a `request abroted` when the backend is killed. But the timeout is >10 seconds - this is too long to respond from the auth server.

Something is wrong with the communication between both.

If I log off and log in again, the fetching of the mediafile works for some time again. -> I strongly suspect the refreshing mechanism to hang in the auth service.

**Comment by GabrielInTheWorld** [comment]
I will implement more debugging output, but I think, this is not an issue from the auth-service. 
This error is thrown, every time the client sends a request to `system/presenter/handle_request`.

**Comment by GabrielInTheWorld** [comment]
> I will implement more debugging output, but I think, this is not an issue from the auth-service.
> This error is thrown, every time the client sends a request to `system/presenter/handle_request`.

Okay, I found a solution and I think, I know, why this error occurred:

In the auth-service is a server made by `express-js`. Express uses its built-in middleware to parse the body-property of a request to JSON. The backend sends a request to validate and refresh a ticket, but then the body of the request is `undefined`.
I think, this throws an error in the middleware, but the error is not shown.

**Comment by FinnStutzenstein** [comment]
is `undefined` the same as an empty string? is so, an empty string is not a valid json string -> This should result in a clean 400er Error. Also this request is send via the authlib, right? Do you send a request payload there?
