### ISSUE TITLE
Read cookie and token rsa key from env var instead of file in keys dir

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-auth-service#66]
I would like to provide the two keys (generated with the script [here](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docker/setup-prod.sh)) to the service via env variable. I want to avoid using a volume in docker compose.

**Comment by FinnStutzenstein** [comment]
For the prod setup, we are going to move to docker secrets. If this is implemented it must be made sure, that these env variables cannot be read in prod mode.

**Comment by GabrielInTheWorld** [comment]
> I would like to provide the two keys (generated with the script [here](https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docker/setup-prod.sh)) to the service via env variable. I want to avoid using a volume in docker compose.

As you can see in the following, keys are already read from environment:
```ts
    private loadKeys(): void {
        Logger.debug('KeyService.loadKeys -- is in dev-mode:', Config.isDevMode());
        if (!process.env.AUTH_TOKEN_KEY && !Config.isDevMode()) {
            throw new Error('No token key defined.');
        }
        this.tokenKey = process.env.AUTH_TOKEN_KEY || AUTH_DEV_KEY;


        if (!process.env.AUTH_COOKIE_KEY && !Config.isDevMode()) {
            throw new Error('No cookie key defined.');
        }
        this.cookieKey = process.env.AUTH_COOKIE_KEY || AUTH_DEV_KEY;
```

**Comment by normanjaeckel** [comment]
Ok, should be solved.
