### ISSUE TITLE
docker image too large

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-auth-service#82]
from the dockerfile

https://github.com/OpenSlides/openslides-auth-service/blob/8a32b4ac03ddf40765c15dea44b703b5fa1370c4/Dockerfile#L3-L4

either remove these lines and take a smaller image or clear the apt-chache after executing, the image is currently 2GB

**Comment by GabrielInTheWorld** [comment]
After spending some time to investigate this behaviour, I found, that these external packages are not the reason for the huge image-size. The reason is the initial docker-image.
